"""
Smart PUC — LaTeX table generator.

Reads the JSON reports produced by the other benchmark scripts and emits
paper-ready LaTeX tables (booktabs style). Each table is written to a
separate ``.tex`` file under ``docs/latex/`` so the paper can \\input{}
individual tables.

Inputs
------
- ``docs/gas_report.json``        (from ``scripts/measure_gas.js``)
- ``docs/ces_vs_co2_report.json`` (from ``scripts/bench_ces_vs_co2.py``)
- ``docs/fraud_eval_report.json`` (from ``python -m ml.fraud_evaluation``)
- ``docs/bench_latency.json``     (from ``scripts/bench_latency.py``)
- ``docs/bench_throughput.json``  (from ``scripts/bench_throughput.py``)

All inputs are optional — the generator emits the tables it can and
prints a warning for the rest. Safe to re-run as a dry build after every
benchmark.

Usage
-----
    python scripts/generate_latex_tables.py
    python scripts/generate_latex_tables.py --out docs/latex
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from typing import Any, Dict, List, Optional


def _read_json(path: str) -> Optional[Dict[str, Any]]:
    if not os.path.exists(path):
        return None
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def _escape(text: str) -> str:
    """Escape LaTeX special characters in human-readable text."""
    return (
        str(text)
        .replace("\\", "\\textbackslash{}")
        .replace("&", "\\&")
        .replace("%", "\\%")
        .replace("$", "\\$")
        .replace("#", "\\#")
        .replace("_", "\\_")
        .replace("{", "\\{")
        .replace("}", "\\}")
    )


# ─────────────────────────── Tables ─────────────────────────────────────

def table_gas(report: Dict[str, Any]) -> str:
    """Per-operation gas cost table."""
    lines = [
        "% Auto-generated by scripts/generate_latex_tables.py",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Smart PUC per-operation gas cost (UUPS-proxied, Solidity 0.8.21, $\\mathtt{viaIR}$ + 200 optimizer runs).}",
        "\\label{tab:gas}",
        "\\begin{tabular}{lrrr}",
        "\\toprule",
        "Operation & Gas & Polygon USD & Ethereum USD \\\\",
        "\\midrule",
    ]
    for row in report.get("results", []):
        lines.append(
            f"{_escape(row['operation'])} & "
            f"{int(row['gas']):,} & "
            f"\\${row['polygon_usd']:.5f} & "
            f"\\${row['ethereum_usd']:.2f} \\\\"
        )
    lines += [
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
    ]
    return "\n".join(lines)


def table_ces_vs_co2(report: Dict[str, Any]) -> str:
    cm = report["confusion_matrix"]
    h = report["headline"]
    rates = report["rates"]
    pct_missed = 100.0 * h["fraction_ces_violations_missed_by_co2_only"]

    lines = [
        "% Auto-generated by scripts/generate_latex_tables.py",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{CES vs.\\ CO\\textsubscript{2}-only compliance detection over "
        f"N={report['n_samples']} synthetic WLTC samples (seed={report['seed']}).}}",
        "\\label{tab:ces_vs_co2}",
        "\\begin{tabular}{lr}",
        "\\toprule",
        "Outcome & Count \\\\",
        "\\midrule",
        f"Both pass & {cm['both_pass']} \\\\",
        f"Both fail & {cm['both_fail']} \\\\",
        f"CES fail / CO\\textsubscript{{2}} pass (\\textbf{{missed by CO\\textsubscript{{2}}-only}}) & {cm['ces_fail_only']} \\\\",
        f"CES pass / CO\\textsubscript{{2}} fail & {cm['co2_fail_only']} \\\\",
        "\\midrule",
        f"CES failure rate & {rates['ces_failure_rate']:.1%} \\\\",
        f"CO\\textsubscript{{2}}-only failure rate & {rates['co2_only_failure_rate']:.1%} \\\\",
        f"Cohen's $\\kappa$ (agreement) & {rates['cohens_kappa']:.3f} \\\\",
        f"\\textbf{{CES violations missed by CO\\textsubscript{{2}}-only}} & \\textbf{{{pct_missed:.1f}\\%}} \\\\",
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
    ]

    # Per-pollutant breakdown of missed cases
    breakdown = h.get("dominant_pollutant_breakdown") or {}
    if breakdown:
        lines += [
            "",
            "\\begin{table}[t]",
            "\\centering",
            "\\caption{Dominant non-CO\\textsubscript{2} pollutant for the "
            "\\textbf{CES-caught / CO\\textsubscript{2}-missed} cases.}",
            "\\label{tab:ces_missed_breakdown}",
            "\\begin{tabular}{lr}",
            "\\toprule",
            "Dominant pollutant & Cases \\\\",
            "\\midrule",
        ]
        for pollutant in ("nox", "pm25", "co", "hc"):
            label = {
                "nox": "NO\\textsubscript{x}",
                "pm25": "PM\\textsubscript{2.5}",
                "co": "CO",
                "hc": "HC",
            }[pollutant]
            lines.append(f"{label} & {breakdown.get(pollutant, 0)} \\\\")
        lines += [
            "\\bottomrule",
            "\\end{tabular}",
            "\\end{table}",
        ]
    return "\n".join(lines)


def table_fraud_eval(report: Dict[str, Any]) -> str:
    metrics = report.get("metrics") or report
    lines = [
        "% Auto-generated by scripts/generate_latex_tables.py",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Fraud detector performance on the synthetic adversarial benchmark.}",
        "\\label{tab:fraud_eval}",
        "\\begin{tabular}{lr}",
        "\\toprule",
        "Metric & Value \\\\",
        "\\midrule",
    ]
    for key in ("precision", "recall", "f1", "f1_score", "auc", "accuracy"):
        if key in metrics:
            lines.append(f"{key.capitalize()} & {float(metrics[key]):.3f} \\\\")
    # Also include per-attack-type breakdown if present
    breakdown = report.get("per_attack_type") or report.get("by_attack")
    if isinstance(breakdown, dict):
        lines += ["\\midrule", "Attack type & Detection rate \\\\", "\\midrule"]
        for attack, val in breakdown.items():
            if isinstance(val, dict):
                val = val.get("detection_rate", val.get("recall", 0))
            lines.append(f"{_escape(attack)} & {float(val):.2f} \\\\")
    lines += [
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
    ]
    return "\n".join(lines)


def table_latency(report: Dict[str, Any]) -> str:
    lines = [
        "% Auto-generated by scripts/generate_latex_tables.py",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{End-to-end per-record latency over "
        f"N={report.get('n_samples', '?')} sequential submissions.}}",
        "\\label{tab:latency}",
        "\\begin{tabular}{lrrr}",
        "\\toprule",
        "Stage & p50 (ms) & p95 (ms) & p99 (ms) \\\\",
        "\\midrule",
    ]
    stages = report.get("stages") or report.get("percentiles") or {}
    if isinstance(stages, dict):
        for stage, pct in stages.items():
            if isinstance(pct, dict):
                lines.append(
                    f"{_escape(stage)} & "
                    f"{float(pct.get('p50', pct.get('median', 0))):.1f} & "
                    f"{float(pct.get('p95', 0)):.1f} & "
                    f"{float(pct.get('p99', 0)):.1f} \\\\"
                )
    lines += [
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
    ]
    return "\n".join(lines)


def table_throughput(report: Dict[str, Any]) -> str:
    lines = [
        "% Auto-generated by scripts/generate_latex_tables.py",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Sustained throughput vs.\\ worker concurrency.}",
        "\\label{tab:throughput}",
        "\\begin{tabular}{rrrr}",
        "\\toprule",
        "Workers & TPS & p50 lat. (ms) & p95 lat. (ms) \\\\",
        "\\midrule",
    ]
    for row in report.get("results", []):
        lines.append(
            f"{int(row.get('workers', 0))} & "
            f"{float(row.get('tps', 0)):.1f} & "
            f"{float(row.get('p50_latency_ms', 0)):.1f} & "
            f"{float(row.get('p95_latency_ms', 0)):.1f} \\\\"
        )
    lines += [
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
    ]
    return "\n".join(lines)


# ─────────────────────────── Entry point ────────────────────────────────

TABLE_SPECS = [
    ("gas_report.json",         "gas_table.tex",         table_gas),
    ("ces_vs_co2_report.json",  "ces_vs_co2_table.tex",  table_ces_vs_co2),
    ("fraud_eval_report.json",  "fraud_eval_table.tex",  table_fraud_eval),
    ("bench_latency.json",      "latency_table.tex",     table_latency),
    ("bench_throughput.json",   "throughput_table.tex",  table_throughput),
]


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate LaTeX tables from benchmark JSON")
    parser.add_argument(
        "--input-dir",
        default=os.path.join(os.path.dirname(__file__), "..", "docs"),
        help="Directory containing the *.json benchmark reports",
    )
    parser.add_argument(
        "--out",
        default=os.path.join(os.path.dirname(__file__), "..", "docs", "latex"),
        help="Output directory for generated .tex files",
    )
    args = parser.parse_args()

    in_dir = os.path.abspath(args.input_dir)
    out_dir = os.path.abspath(args.out)
    os.makedirs(out_dir, exist_ok=True)

    wrote_any = False
    for in_name, out_name, builder in TABLE_SPECS:
        in_path = os.path.join(in_dir, in_name)
        out_path = os.path.join(out_dir, out_name)
        data = _read_json(in_path)
        if not data:
            print(f"[skip] {in_name} not found — run the corresponding benchmark first.")
            continue
        try:
            tex = builder(data)
        except Exception as exc:
            print(f"[error] Could not build {out_name} from {in_name}: {exc}")
            continue
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(tex + "\n")
        print(f"[ok]   wrote {out_path}")
        wrote_any = True

    if not wrote_any:
        print(
            "\nNo tables written. Run at least one benchmark first, e.g.:\n"
            "  python scripts/bench_ces_vs_co2.py --samples 5000\n"
            "  npx hardhat run scripts/measure_gas.js\n",
        )
        sys.exit(1)


if __name__ == "__main__":
    main()
